name: Android Tools AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/15 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |
        sudo apt update
        sudo apt install libfuse2 desktop-file-utils
        wget https://raw.githubusercontent.com/Samueru-sama/android-tools-AppImage/main/android-tools-appimage.sh
        chmod a+x ./android-tools-appimage.sh
        ./android-tools-appimage.sh
        mkdir dist
        mv *AppImage dist/

    - name: Check version file
      run: |
       cat ~/version
       echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: AppImage
        path: 'dist'
        
    - name: Upload version file
      uses: actions/upload-artifact@v4.6.1
      with:
       name: version
       path: ~/version
    
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage
        - uses: actions/download-artifact@v4.1.8
          with:
            name: version

        - name: Read version
          run: |
            cat version
            export VERSION="$(<version)"
            echo "APP_VERSION=${VERSION}" >> "${GITHUB_ENV}"
    
        #Version Release
        - name: Del Previous Release
          run: |
            gh release delete "${APP_VERSION}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag  -y
          env:
            GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          continue-on-error: true
        - name: Continuous Releaser
          uses: softprops/action-gh-release@v2
          with:
            name: "Android Tools AppImage ${{ env.APP_VERSION}}"
            tag_name: "${{ env.APP_VERSION}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: true
            files: |
              *.AppImage*
          continue-on-error: false

        #Snapshot Release
        - name: Get Date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: Snapshot Releaser
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot ${{ env.APP_VERSION}}"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false
          
  soar-nest:
    needs: [release] #Only runs if release succeeded
    permissions:
      attestations: write #Needed for Build Provenance & Attestations
      contents: write #Needed to create Release
      id-token: write #Needed for Build Provenance & Attestations
      packages: write #Needed to push to ghcr
    uses: "pkgforge/soarpkgs/.github/workflows/matrix_builds.yaml@main"
    with:
      host: "x86_64-Linux" #Otherwise aarch64-Linux OR ALL for both
      sbuild-url: "https://raw.githubusercontent.com/pkgforge/soarpkgs/refs/heads/main/packages/android-tools/appimage.pkgforge-dev.stable.yaml" #RAW URL to the SBUILD Recipe, can be hosted anywhere
      ghcr-url: "ghcr.io/${{ github.repository }}/stable" #Package will be pushed under this path
      pkg-family: "android-tools" #Needed to generate tags & artifact names
      banner: true #If false, then Disables PkgForge Branding in LogFiles
      debug: false #If set to true, will run everything with set -x
      logs: true #Will Attach the entire Logs + File as Workflow Artifact
      rebuild: true #Will rebuild even if ghcr tag already exists
